### ISSUE TITLE
Bug: users unsubbers

### ISSUE THREAD

**Issue by acimanx** [Antrikshy/Unsubber#2]
Something's wrong when checking /u/ subreddits, they're treated wrong with the app

**Comment by Antrikshy** [comment]
Thanks for the report! I didn't think to test this. I'm looking into it.

**Comment by Antrikshy** [comment]
I decided to just skip over users for a couple of reasons.

1. Unsubber relies on endpoints such as [this one](https://www.reddit.com/r/movies/new.json), which aren't populated [for users](https://www.reddit.com/user/AutoModerator/new.json).
2. The heuristics I came up with for detecting inactive subreddits won't translate to users, requiring a lot of design to properly support users.

The change should be live now!
